export default {
  acceptInvite: '/accept/:token',
  account: '/account',
  activity: '/activity',
  apiKeys: '/api-keys',
  confirmPassword: '/confirm-password',
  dashboard: '/',
  dataExports: '/exports',
  demo: '/demo',
  events: '/events',
  forgotPass: '/forgot',
  leaderboards: '/leaderboards',
  leaderboardEntries: '/leaderboards/:internalName',
  login: '/',
  organisation: '/organisation',
  players: '/players',
  playerProps: '/players/:id/props',
  playerEvents: '/players/:id/events',
  playerStats: '/players/:id/stats',
  register: '/register',
  recover: '/recover',
  stats: '/stats',
  verify2FA: '/verify'
}
